# Image Python officielle
FROM python:3.11-slim

# Dossier de travail
WORKDIR /app

# Copier les fichiers
COPY . /app

# Installer Flask
RUN pip install flask

# Port exposé
EXPOSE 5000

# Commande de lancement
CMD ["python", "app.py"]